// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Proba1.Migrations
{
    [DbContext(typeof(DestilerijaContext))]
    [Migration("20220207194549_v6")]
    partial class v6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Burad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int?>("ProizvodID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProizvodID");

                    b.ToTable("Burad");
                });

            modelBuilder.Entity("Models.Proizvod", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Proizvod");
                });

            modelBuilder.Entity("Models.Proizvodnja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BuradID")
                        .HasColumnType("int");

                    b.Property<int?>("RadnikID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BuradID");

                    b.HasIndex("RadnikID");

                    b.ToTable("Proizvodnja");
                });

            modelBuilder.Entity("Models.Radnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Radnik");
                });

            modelBuilder.Entity("Models.Burad", b =>
                {
                    b.HasOne("Models.Proizvod", "Proizvod")
                        .WithMany("Burad")
                        .HasForeignKey("ProizvodID");

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("Models.Proizvodnja", b =>
                {
                    b.HasOne("Models.Burad", "Burad")
                        .WithMany("Proizvodnja")
                        .HasForeignKey("BuradID");

                    b.HasOne("Models.Radnik", "Radnik")
                        .WithMany("Proizvodnja")
                        .HasForeignKey("RadnikID");

                    b.Navigation("Burad");

                    b.Navigation("Radnik");
                });

            modelBuilder.Entity("Models.Burad", b =>
                {
                    b.Navigation("Proizvodnja");
                });

            modelBuilder.Entity("Models.Proizvod", b =>
                {
                    b.Navigation("Burad");
                });

            modelBuilder.Entity("Models.Radnik", b =>
                {
                    b.Navigation("Proizvodnja");
                });
#pragma warning restore 612, 618
        }
    }
}
